### ISSUE TITLE
Cmake failed on issue like "version gcc need at least version 13.1” ...

### ISSUE THREAD

**Issue by zhangshaoshuai** [not-chciken/TLMBoy#3]
hello bro, thank you so much for your so wonderful sharing.
I met a issue like "version gcc need at least version 13.1” , but I really have no any experience to update or use multi-version of gcc...
So could you please teach us how did you perform your installation on your linux pc? 
Mine linux verison  : WSL2.0 unbuntu 22.04
Gcc version  ：11.4

THANK U.

**Comment by zhangshaoshuai** [comment]
I have installed GCC13.1  on my WSL, it compiled successfully ,but when I run the tlmboy, it shows " No ROM path was specified!" . I tried some way to fix it ,but all are failed ...

**Comment by zhangshaoshuai** [comment]
and while I tried to add the -r option with ../roms/DMG_ROM.bin , there shows a new error as :
tlmboy: /home/shaoshuai/vp_vcml_gameboy/TLMBoy/src/generic_memory.cpp:46: virtual void GenericMemory::LoadFromFile(std::filesystem::__cxx11::path, int): Assertion `size >= offset' failed.
Aborted (core dumped)

**Comment by zhangshaoshuai** [comment]
I have no idea about what to do next...

**Comment by not-chciken** [comment]
I'll take a look ;)

**Comment by not-chciken** [comment]
The path assigned to "-r" must be a game ROM, not the boot ROM.
I added some clarification in the README (see "Usage").
Furthermore, the homebrew game FlappyBoy is now included as an example.
